### PR TITLE
Add Open in Kaggle badge

### PR DESCRIPTION
**Pull request by pizzaz93**
Add Kaggle Badge that allows for opening the .ipynb as a Kaggle Notebook as seen here https://www.kaggle.com/product-feedback/152480.

### CODE REVIEW

**Comment by yuval-alaluf** [comment]
@Johnsel 
Thanks for the contribution! 
I am not too familiar with what kaggle's environment has to offer over, say, Google Colab. Are there additional features they offer? 
In any case, if you have already added a badge for kaggle, I would also add a badge for Colab on the way :) 
You can find an example here: https://github.com/eladrich/pixel2style2pixel/pull/79

**Comment by pizzaz93** [comment]
You're welcome Yuval, I can definitely add that into the PR.

**Comment by pizzaz93** [comment]
I've added an "Open in Colab" badge.

Some advantages of Kaggle over Colab:
- Kaggle has a very large and comprehensive maintained docker image, whereas Colab's is much smaller and therefore you have to do more pip install statements etc.
- Kaggle has better dataset integrations, where data is pre-cached and ready instantaneously, with no need to download it into your notebook, like you have to do in Colab.

**Comment by yuval-alaluf** [comment]
Awesome! Thanks for introducing me to the Kaggle environment, I hope to try it out soon. 
Merging your changes now. Thanks again.

**Pull request merged**
